[dashboard_config]
dashboard_url = "https://625868cd-b250-48c0-9a0f-4bd04a536e69.nonprod.uoe.choreoapps.dev/dashboard/api/"
management_hostname = "f5aad5f4-4cac-40df-b0ed-e0c3ca8ae985-dev-internal.nonprod-internal.uoe.choreoapis.dev/wso2testing/mimessagestore/mi-management-api-http/v1.0"

[management_api]
protocols = "http"
